version: '3.8'

services:
  presensi-app:
    image: ghcr.io/wahid672/absensidigital:latest
    container_name: presensi-app
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - caddy_net
    volumes:
      - presensi_data:/app/data
    environment:
      - PORT=8080
      - DB_PATH=/app/data/presensi.db
      - JWT_SECRET=siakad_esp32_iot_secret_key_2026
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - TZ=Asia/Jakarta
      - DEMO_MODE=false # Ubah ke 'true' untuk mengaktifkan Versi Demo (read-only master data & pengaturan)
    labels:
      - "com.centurylinklabs.watchtower.scope=presensi"

networks:
  caddy_net:
    external: true

volumes:
  presensi_data:
    name: presensi_data
